# Generated by Django 4.2.2 on 2023-06-09 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55)),
                ('pub_date', models.DateTimeField()),
                ('image', models.ImageField(upload_to='article/images')),
            ],
        ),
    ]
